### ISSUE TITLE
Add DSIG members

### ISSUE THREAD

**Issue by pbuttigieg** [iodepo/OceanDecade-dsig#2]
DSIG members wishing to contribute directly to this repository are invited to list their usernames here.

Members that have been granted write permissions will have their comments marked with a 🚀

**Comment by sio-spc** [comment]
@pbuttigieg here's mine: sio-spc

**Comment by SnaggyD** [comment]
Conor Delaney (snaggyd)
I am here: https://github.com/SnaggyD

**Comment by aidy888** [comment]
aidy888

**Comment by CorinneBassin-SOI** [comment]
CorinneBassin-SOI

**Comment by pbuttigieg** [comment]
> aidy888

Hi @aidy888 - would you mind identifying yourself?

**Comment by pbuttigieg** [comment]
@aurelianogentile

**Comment by peteapostle** [comment]
@peteapostle
Pete Apostle
Geo-Data Production Manager, Americas
Fugro
M 1-510-417-9894
E [p.apostle@fugro.com](mailto:p.apostle@fugro.com) 
A 1777 Botelho Drive, Suite 262, Walnut Creek, CA 94596, USA

**Comment by andrainaKool** [comment]
Tinah Martin
Lead Data Manager
Seabed 2030 Regional Center for the Atlantic and Indian Oceans
Lamont-Doherty Earth Observatory of Columbia University

**Comment by LDemargne** [comment]
Louis Demargne, Data & Knowledge Management Officer at IOC/UNESCO, embedded in the Ocean Decade Coordination Unit (DCU)

**Comment by kevin-obrien** [comment]
Kevin O'Brien, Senior Research Scientist, University of Washington/CICOES, NOAA/PMEL, GOOS OCG Vice-chair for Data and Information.

**Comment by pramod-thupaki** [comment]
pramod-thupaki - https://github.com/pramod-thupaki

**Comment by ltybergh** [comment]
Lennert Tyberghein (ltybergh)
https://github.com/ltybergh

**Comment by wichor** [comment]
Marcin Wichorowski (wichor)
https://github.com/wichor

**Comment by carolmazzuco** [comment]
Ana Carolina Mazzuco :)
https://github.com/carolmazzuco

**Comment by annocean** [comment]
Anna Silyakova, Science Lead, [HUB Ocean](https://www.hubocean.earth/)

**Comment by GregReed98** [comment]
Greg Reed https://github.com/GregReed98

**Comment by pipbricher** [comment]
Pip Bricher here.

**Comment by pbuttigieg** [comment]
> @pbuttigieg please send an invitation to edit the repo to @diodon

crosslink to #10

**Comment by TRasehlomi** [comment]
@pbuttigieg please add Tshikana   https://github.com/TRasehlomi

**Comment by pbuttigieg** [comment]
I think this is closed - new issues can be opened for new members
